const fs = require('node:fs');
const path = require('node:path');

const symbolsPath = path.resolve("./symbols");

const isSvgFile = (fileName) => {
  return fs.lstatSync(fileName).isFile() && fileName.endsWith(".svg");
};

const files = fs.readdirSync(symbolsPath)
  .map(fileName => {
    return path.join(symbolsPath, fileName);
  })
  .filter(isSvgFile);

const SvgMap = {};
for (const file of files) {
  const name = path.parse(file).name;
  const data = fs.readFileSync(file, 'utf8');
  SvgMap[name] = data;
}

const content = `// Autogenerated file of all symbols as single javascript default object.\n
export default ${JSON.stringify(SvgMap, null, 2)};
`;

fs.writeFile("./index.js", content, err => {
  if (err) {
    console.error(err);
  }
});

const declaration = "declare const symbols: Record<string, string>;\nexport default symbols;\n";

fs.writeFile("./index.d.ts", declaration, err => {
  if (err) {
    console.error(err);
  }
});
